site_name: 'Vapor Cloud Docs'
copyright: 'Copyright &copy; 2017 Qutheory, LLC'
markdown_extensions:
      - admonition
      - footnotes
      - codehilite:
          guess_lang: false
      - meta
      - toc:
          permalink: true

theme:
    name: 'material'
    palette:
        primary: 'blue'
        accent: 'purple'
    logo: 'images/white-cloud-icon.svg'

repo_url: http://github.com/vapor-cloud/documentation
edit_uri: https://github.com/vapor-cloud/documentation/edit/master/docs/


extra:
      logo: 'images/white-cloud-icon.svg'
      social:
        - type: 'twitter'
          link: 'https://twitter.com/@codevapor'
        - type: 'slack'
          link: 'http://vapor.team/'
      font:
        text: 'Roboto Slab'
        code: 'Source Code Pro'

extra_css:
  - 'stylesheets/extra.css'

pages:
- Overview: 'index.md'
- Quick Start: 'quick-start.md'
- Architecture:
    - 'Core principles': 'architecture/core-principles.md'
- Toolbox:
    - 'Install': 'toolbox/install.md'
    - 'Getting Started': 'toolbox/getting-started.md'
    - 'Managing your apps': 'toolbox/managing-your-apps.md'
- cloud.yml:
    - 'General': 'configuration/general.md'
    - Vapor:
        - 'Basic': 'configuration/vapor/basic.md'
        - 'Custom config': 'configuration/vapor/custom-config.md'
    - 'Blank': 'configuration/blank.md'
- Advanced:
    - General:
        - 'About our server setup': 'advanced/general/about-our-server-setup.md'
        - 'Timezone settings': 'advanced/general/timezone-settings.md'
        - 'How do cronjobs work': 'advanced/general/how-do-cronjobs-work.md'
        - 'Sending E-mails (SMTP)': 'advanced/general/sending-emails.md'
        - 'Using private git repository': 'advanced/general/using-private-git.md'
        - 'Running load tests': 'advanced/general/load-testing.md'
    - Loadbalancer:
        - 'SSL/TLS': 'advanced/loadbalancer/ssl-tls.md'
    - Security:
        - 'Responsibilities': 'advanced/security/responsibilities.md'
        - 'Your responsibilities': 'advanced/security/your-responsibilities.md'
        - 'Vapor Cloud security': 'advanced/security/vapor-cloud-security.md'
    - Limitation:
        - 'Requests': "advanced/limitation/requests.md"
- Database:
  - 'MySQL': 'database/mysql.md'
  - 'MongoDB': 'database/mongodb.md'
  - 'PostgreSQL': 'database/postgresql.md'
  - 'Your own database server': 'database/your-own-database-server.md'
  - Beta:
      - 'Database general': 'database/beta/database-general.md'
      - 'Plans': 'database/beta/plans.md'
      - 'Getting started': 'database/beta/getting-started.md'
      - 'External access': 'database/beta/external-access.md'
      - 'Features': 'database/beta/features.md'
      - 'Backups': 'database/beta/backups.md'
      - 'Config files': 'database/beta/config-files.md'
      - 'Technical information': 'database/beta/technical-information.md'
- Domain:
    - 'Add custom domain': "custom-domain/add-domain.md"
    - 'Certificate manager': "custom-domain/certificate-manager.md"
- Troubleshooting:
    - 'Troubleshooting': 'troubleshooting/troubleshooting.md'
    - 'Redis': 'troubleshooting/redis.md'
    - 'MySQL': 'troubleshooting/mysql.md'
- Delete:
    - 'Application': 'delete/delete-application.md'
    - 'Database': 'delete/delete-database.md'
- Support:
    - 'Contact support': 'support/contact-support.md'
- 'FAQ': 'FAQ.md'
- Shutdown:
    - 'Shutdown': 'shutdown/index.md'
    - 'Migrate to Heroku': 'shutdown/migrate-to-heroku.md'